apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databases.selfservice.ovh
spec:
  group: selfservice.ovh
  names:
    kind: Database  
    plural: databases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                    default: 20
                  engine:
                    type: string
                    default: postgres
                    enum:
                      - postgres
                      - mysql
                  version:
                    type: string
                    default: "13"
                required:
                  - storageGB
                  - engine
                  - version
            required:
              - parameters
  claimNames:
    kind: Database
    plural: databases
