apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: database-postgres-ovh
spec:
  writeConnectionSecretsToRef:
    namespace: crossplane-system
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: ovh-config
  compositeTypeRef:
    apiVersion: selfservice.ovh/v1alpha1
    kind: Database
  resources:
    - name: databaseinstance
      base:
        apiVersion: databases.ovh.edixos.io/v1alpha1
        kind: ProjectDatabase
        spec:
          forProvider:
            engine: postgres
            version: "16"
            plan: essential
            flavor: db1-4
            diskSize: 20
            nodes:
              - region: GRA
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.engine
          toFieldPath: spec.forProvider.engine
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.version
          toFieldPath: spec.forProvider.version
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.diskSize
        - type: FromEnvironmentFieldPath
          fromFieldPath: projectId
          toFieldPath: spec.forProvider.serviceName

    - name: databaseuser
      base:
        apiVersion: databases.ovh.edixos.io/v1alpha1
        kind: ProjectDatabaseUser
        spec:
          forProvider:
            engine: postgres
            name: admin
            clusterIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.engine
          toFieldPath: spec.forProvider.engine
        - type: FromEnvironmentFieldPath
          fromFieldPath: projectId
          toFieldPath: spec.forProvider.serviceName
