apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: database-postgres-ovh
spec:
  compositeTypeRef:
    apiVersion: selfservice.ovh/v1alpha1
    kind: Database
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: databaseinstance
            base:
              apiVersion: databases.ovh.edixos.io/v1alpha1
              kind: ProjectDatabase
              spec:
                forProvider:
                  engine: postgresql
                  version: "16"
                  plan: discovery
                  flavor: b3-8
                  diskSize: 10
                  serviceName: "4835abd389014831a84994db5635fc1a"
                  nodes:
                    - region: GRA
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.engine
                toFieldPath: spec.forProvider.engine
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.version
                toFieldPath: spec.forProvider.version
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.plan
                toFieldPath: spec.forProvider.plan
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.flavor
                toFieldPath: spec.forProvider.flavor

          - name: databaseuser
            base:
              apiVersion: databases.ovh.edixos.io/v1alpha1
              kind: ProjectDatabaseUser
              spec:
                forProvider:
                  engine: postgresql
                  name: admin
                  serviceName: "4835abd389014831a84994db5635fc1a"
                  clusterIdSelector:
                    matchControllerRef: true
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.engine
                toFieldPath: spec.forProvider.engine
