apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databasestacks.selfservice.ovh
spec:
  group: selfservice.ovh
  names:
    kind: DatabaseStack
    plural: databasestacks
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  engine:
                    type: string
                    default: postgresql
                    enum:
                      - postgresql
                      - mysql
                  version:
                    type: string
                    default: "16"
                  plan:
                    type: string
                    default: discovery
                    enum:
                      - discovery
                      - production
                  flavor:
                    type: string
                    default: b3-8
                    enum:
                      - b3-8
                      - b3-16
                required:
                  - engine
                  - version
            required:
              - parameters
  claimNames:
    kind: DatabaseStack
    plural: databasestacks
