apiVersion: selfservice.ovh/v1alpha1
kind: AIDatabase
metadata:
  name: shop-postgres
  namespace: default
spec:
  parameters:
    engine: postgresql
    version: "16"
    workloadDescription: >
      Plateforme e-commerce pour une marque de retail ouest-africaine.
      Environ 800 utilisateurs concurrents attendus aux heures de pointe
      (soldes Ramadan/Tabaski). Trafic de lecture important sur le catalogue
      produit, écritures transactionnelles pour les commandes.
      Haute disponibilité requise. Les données doivent être conservées 3 ans.
  compositionRef:
    name: aidatabase-postgres-ovh
