apiVersion: selfservice.ovh/v1alpha1
kind: Database
metadata:
  name: demo-postgres-db
  namespace: default
spec:
  parameters:
    engine: postgresql
    version: "16"
    plan: discovery
    flavor: b3-8
  compositionRef:
    name: database-postgres-ovh
